// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v6.32.1
// source: api/protos/transaction.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RuleEngineClient is the client API for RuleEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RuleEngineClient interface {
	AnalyzeTransaction(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*RiskResult, error)
}

type ruleEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewRuleEngineClient(cc grpc.ClientConnInterface) RuleEngineClient {
	return &ruleEngineClient{cc}
}

func (c *ruleEngineClient) AnalyzeTransaction(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*RiskResult, error) {
	out := new(RiskResult)
	err := c.cc.Invoke(ctx, "/risk.RuleEngine/AnalyzeTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RuleEngineServer is the server API for RuleEngine service.
// All implementations must embed UnimplementedRuleEngineServer
// for forward compatibility
type RuleEngineServer interface {
	AnalyzeTransaction(context.Context, *Transaction) (*RiskResult, error)
	mustEmbedUnimplementedRuleEngineServer()
}

// UnimplementedRuleEngineServer must be embedded to have forward compatible implementations.
type UnimplementedRuleEngineServer struct {
}

func (UnimplementedRuleEngineServer) AnalyzeTransaction(context.Context, *Transaction) (*RiskResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnalyzeTransaction not implemented")
}
func (UnimplementedRuleEngineServer) mustEmbedUnimplementedRuleEngineServer() {}

// UnsafeRuleEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RuleEngineServer will
// result in compilation errors.
type UnsafeRuleEngineServer interface {
	mustEmbedUnimplementedRuleEngineServer()
}

func RegisterRuleEngineServer(s grpc.ServiceRegistrar, srv RuleEngineServer) {
	s.RegisterService(&RuleEngine_ServiceDesc, srv)
}

func _RuleEngine_AnalyzeTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Transaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleEngineServer).AnalyzeTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/risk.RuleEngine/AnalyzeTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleEngineServer).AnalyzeTransaction(ctx, req.(*Transaction))
	}
	return interceptor(ctx, in, info, handler)
}

// RuleEngine_ServiceDesc is the grpc.ServiceDesc for RuleEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RuleEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "risk.RuleEngine",
	HandlerType: (*RuleEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnalyzeTransaction",
			Handler:    _RuleEngine_AnalyzeTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/protos/transaction.proto",
}

// PersistenceClient is the client API for Persistence service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PersistenceClient interface {
	StoreTransaction(ctx context.Context, in *RiskResult, opts ...grpc.CallOption) (*StoreAck, error)
}

type persistenceClient struct {
	cc grpc.ClientConnInterface
}

func NewPersistenceClient(cc grpc.ClientConnInterface) PersistenceClient {
	return &persistenceClient{cc}
}

func (c *persistenceClient) StoreTransaction(ctx context.Context, in *RiskResult, opts ...grpc.CallOption) (*StoreAck, error) {
	out := new(StoreAck)
	err := c.cc.Invoke(ctx, "/risk.Persistence/StoreTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PersistenceServer is the server API for Persistence service.
// All implementations must embed UnimplementedPersistenceServer
// for forward compatibility
type PersistenceServer interface {
	StoreTransaction(context.Context, *RiskResult) (*StoreAck, error)
	mustEmbedUnimplementedPersistenceServer()
}

// UnimplementedPersistenceServer must be embedded to have forward compatible implementations.
type UnimplementedPersistenceServer struct {
}

func (UnimplementedPersistenceServer) StoreTransaction(context.Context, *RiskResult) (*StoreAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreTransaction not implemented")
}
func (UnimplementedPersistenceServer) mustEmbedUnimplementedPersistenceServer() {}

// UnsafePersistenceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PersistenceServer will
// result in compilation errors.
type UnsafePersistenceServer interface {
	mustEmbedUnimplementedPersistenceServer()
}

func RegisterPersistenceServer(s grpc.ServiceRegistrar, srv PersistenceServer) {
	s.RegisterService(&Persistence_ServiceDesc, srv)
}

func _Persistence_StoreTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RiskResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersistenceServer).StoreTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/risk.Persistence/StoreTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersistenceServer).StoreTransaction(ctx, req.(*RiskResult))
	}
	return interceptor(ctx, in, info, handler)
}

// Persistence_ServiceDesc is the grpc.ServiceDesc for Persistence service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Persistence_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "risk.Persistence",
	HandlerType: (*PersistenceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StoreTransaction",
			Handler:    _Persistence_StoreTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/protos/transaction.proto",
}
