// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v6.32.1
// source: api/protos/transaction.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RuleEngineClient is the client API for RuleEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RuleEngineClient interface {
	AnalyzeTransaction(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*RiskResult, error)
}

type ruleEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewRuleEngineClient(cc grpc.ClientConnInterface) RuleEngineClient {
	return &ruleEngineClient{cc}
}

func (c *ruleEngineClient) AnalyzeTransaction(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*RiskResult, error) {
	out := new(RiskResult)
	err := c.cc.Invoke(ctx, "/risk.RuleEngine/AnalyzeTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RuleEngineServer is the server API for RuleEngine service.
// All implementations must embed UnimplementedRuleEngineServer
// for forward compatibility
type RuleEngineServer interface {
	AnalyzeTransaction(context.Context, *Transaction) (*RiskResult, error)
	mustEmbedUnimplementedRuleEngineServer()
}

// UnimplementedRuleEngineServer must be embedded to have forward compatible implementations.
type UnimplementedRuleEngineServer struct {
}

func (UnimplementedRuleEngineServer) AnalyzeTransaction(context.Context, *Transaction) (*RiskResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnalyzeTransaction not implemented")
}
func (UnimplementedRuleEngineServer) mustEmbedUnimplementedRuleEngineServer() {}

// UnsafeRuleEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RuleEngineServer will
// result in compilation errors.
type UnsafeRuleEngineServer interface {
	mustEmbedUnimplementedRuleEngineServer()
}

func RegisterRuleEngineServer(s grpc.ServiceRegistrar, srv RuleEngineServer) {
	s.RegisterService(&RuleEngine_ServiceDesc, srv)
}

func _RuleEngine_AnalyzeTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Transaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleEngineServer).AnalyzeTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/risk.RuleEngine/AnalyzeTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleEngineServer).AnalyzeTransaction(ctx, req.(*Transaction))
	}
	return interceptor(ctx, in, info, handler)
}

// RuleEngine_ServiceDesc is the grpc.ServiceDesc for RuleEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RuleEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "risk.RuleEngine",
	HandlerType: (*RuleEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnalyzeTransaction",
			Handler:    _RuleEngine_AnalyzeTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/protos/transaction.proto",
}

// PersistenceClient is the client API for Persistence service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PersistenceClient interface {
	StoreRawTransaction(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*StoreAck, error)
	StoreTransaction(ctx context.Context, in *StoreTransactionRequest, opts ...grpc.CallOption) (*StoreAck, error)
}

type persistenceClient struct {
	cc grpc.ClientConnInterface
}

func NewPersistenceClient(cc grpc.ClientConnInterface) PersistenceClient {
	return &persistenceClient{cc}
}

func (c *persistenceClient) StoreRawTransaction(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*StoreAck, error) {
	out := new(StoreAck)
	err := c.cc.Invoke(ctx, "/risk.Persistence/StoreRawTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *persistenceClient) StoreTransaction(ctx context.Context, in *StoreTransactionRequest, opts ...grpc.CallOption) (*StoreAck, error) {
	out := new(StoreAck)
	err := c.cc.Invoke(ctx, "/risk.Persistence/StoreTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PersistenceServer is the server API for Persistence service.
// All implementations must embed UnimplementedPersistenceServer
// for forward compatibility
type PersistenceServer interface {
	StoreRawTransaction(context.Context, *Transaction) (*StoreAck, error)
	StoreTransaction(context.Context, *StoreTransactionRequest) (*StoreAck, error)
	mustEmbedUnimplementedPersistenceServer()
}

// UnimplementedPersistenceServer must be embedded to have forward compatible implementations.
type UnimplementedPersistenceServer struct {
}

func (UnimplementedPersistenceServer) StoreRawTransaction(context.Context, *Transaction) (*StoreAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreRawTransaction not implemented")
}
func (UnimplementedPersistenceServer) StoreTransaction(context.Context, *StoreTransactionRequest) (*StoreAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreTransaction not implemented")
}
func (UnimplementedPersistenceServer) mustEmbedUnimplementedPersistenceServer() {}

// UnsafePersistenceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PersistenceServer will
// result in compilation errors.
type UnsafePersistenceServer interface {
	mustEmbedUnimplementedPersistenceServer()
}

func RegisterPersistenceServer(s grpc.ServiceRegistrar, srv PersistenceServer) {
	s.RegisterService(&Persistence_ServiceDesc, srv)
}

func _Persistence_StoreRawTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Transaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersistenceServer).StoreRawTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/risk.Persistence/StoreRawTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersistenceServer).StoreRawTransaction(ctx, req.(*Transaction))
	}
	return interceptor(ctx, in, info, handler)
}

func _Persistence_StoreTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersistenceServer).StoreTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/risk.Persistence/StoreTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersistenceServer).StoreTransaction(ctx, req.(*StoreTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Persistence_ServiceDesc is the grpc.ServiceDesc for Persistence service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Persistence_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "risk.Persistence",
	HandlerType: (*PersistenceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StoreRawTransaction",
			Handler:    _Persistence_StoreRawTransaction_Handler,
		},
		{
			MethodName: "StoreTransaction",
			Handler:    _Persistence_StoreTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/protos/transaction.proto",
}

// NotificationClient is the client API for Notification service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotificationClient interface {
	TriggerRiskAlert(ctx context.Context, in *RiskAlertRequest, opts ...grpc.CallOption) (*NotificationAck, error)
}

type notificationClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificationClient(cc grpc.ClientConnInterface) NotificationClient {
	return &notificationClient{cc}
}

func (c *notificationClient) TriggerRiskAlert(ctx context.Context, in *RiskAlertRequest, opts ...grpc.CallOption) (*NotificationAck, error) {
	out := new(NotificationAck)
	err := c.cc.Invoke(ctx, "/risk.Notification/TriggerRiskAlert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationServer is the server API for Notification service.
// All implementations must embed UnimplementedNotificationServer
// for forward compatibility
type NotificationServer interface {
	TriggerRiskAlert(context.Context, *RiskAlertRequest) (*NotificationAck, error)
	mustEmbedUnimplementedNotificationServer()
}

// UnimplementedNotificationServer must be embedded to have forward compatible implementations.
type UnimplementedNotificationServer struct {
}

func (UnimplementedNotificationServer) TriggerRiskAlert(context.Context, *RiskAlertRequest) (*NotificationAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TriggerRiskAlert not implemented")
}
func (UnimplementedNotificationServer) mustEmbedUnimplementedNotificationServer() {}

// UnsafeNotificationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotificationServer will
// result in compilation errors.
type UnsafeNotificationServer interface {
	mustEmbedUnimplementedNotificationServer()
}

func RegisterNotificationServer(s grpc.ServiceRegistrar, srv NotificationServer) {
	s.RegisterService(&Notification_ServiceDesc, srv)
}

func _Notification_TriggerRiskAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RiskAlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServer).TriggerRiskAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/risk.Notification/TriggerRiskAlert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServer).TriggerRiskAlert(ctx, req.(*RiskAlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Notification_ServiceDesc is the grpc.ServiceDesc for Notification service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Notification_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "risk.Notification",
	HandlerType: (*NotificationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TriggerRiskAlert",
			Handler:    _Notification_TriggerRiskAlert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/protos/transaction.proto",
}
